language: ruby
rvm:
- 2.2.5

script:
# - bundle exec jekyll build
 - bundle exec rake build
 - bundle exec htmlproofer --check-external-hash --check-html --check-img-http --check-opengraph --enforce-https --timeframe 6w ./_site

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # https://github.com/gjtorikian/html-proofer/issues/381
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
